# Generated by Django 5.1.6 on 2025-05-25 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('class_ID', models.TextField(blank=True)),
                ('hit_die', models.PositiveSmallIntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')], default=8, help_text='Your class’s Hit Die')),
            ],
        ),
        migrations.CreateModel(
            name='ClassFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('level_prerequisite', models.CharField(blank=True, max_length=512)),
                ('feat_type', models.CharField(max_length=512)),
                ('class_name', models.CharField(blank=True, max_length=512)),
                ('race', models.CharField(blank=True, max_length=512)),
                ('tags', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProficiencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tier', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProficiencyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('bonus', models.IntegerField(help_text='e.g. +2 for Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifier, e.g. 'elf'", max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifier for formulas, e.g. 'bloodline_points'", unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ability', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=501)),
                ('level', models.IntegerField()),
                ('classification', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField()),
                ('effect', models.TextField(blank=True)),
                ('upcast_effect', models.TextField(blank=True)),
                ('saving_throw', models.CharField(blank=True, max_length=512)),
                ('casting_time', models.CharField(max_length=512)),
                ('duration', models.CharField(max_length=512)),
                ('components', models.CharField(max_length=512)),
                ('range', models.CharField(max_length=512)),
                ('target', models.CharField(max_length=512)),
                ('origin', models.CharField(max_length=512)),
                ('sub_origin', models.CharField(blank=True, max_length=512)),
                ('mastery_req', models.CharField(blank=True, max_length=512)),
                ('tags', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_throw_required', models.BooleanField(default=False, help_text='Does this ability allow a saving throw?')),
                ('saving_throw_type', models.CharField(blank=True, choices=[('reflex', 'Reflex'), ('fortitude', 'Fortitude'), ('will', 'Will')], help_text='Which saving throw?', max_length=10, null=True)),
                ('saving_throw_granularity', models.CharField(blank=True, choices=[('basic', 'Basic (Success / Failure)'), ('normal', 'Normal (Crit Success / Success / Failure / Crit Failure)')], help_text='Simple or full save table?', max_length=10, null=True)),
                ('saving_throw_basic_success', models.CharField(blank=True, help_text='What happens on a basic save: Success', max_length=255)),
                ('saving_throw_basic_failure', models.CharField(blank=True, help_text='What happens on a basic save: Failure', max_length=255)),
                ('saving_throw_critical_success', models.CharField(blank=True, help_text='What happens on a full save: Critical Success', max_length=255)),
                ('saving_throw_success', models.CharField(blank=True, help_text='What happens on a full save: Success', max_length=255)),
                ('saving_throw_failure', models.CharField(blank=True, help_text='What happens on a full save: Failure', max_length=255)),
                ('saving_throw_critical_failure', models.CharField(blank=True, help_text='What happens on a full save: Critical Failure', max_length=255)),
                ('damage_type', models.CharField(blank=True, choices=[('physical_bludgeoning', 'Physical Bludgeoning'), ('physical_slashing', 'Physical Slashing'), ('physical_piercing', 'Physical Piercing'), ('explosive', 'Explosive'), ('magical_bludgeoning', 'Magical Bludgeoning'), ('magical_slashing', 'Magical Slashing'), ('magical_piercing', 'Magical Piercing'), ('acid', 'Acid'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('thunder', 'Thunder'), ('true', 'True')], help_text='If this feature deals damage, pick its damage type (optional).', max_length=25, null=True)),
                ('scope', models.CharField(choices=[('class_feat', 'Class Feature'), ('subclass_feat', 'Subclass Feature'), ('subclass_choice', 'Subclass Choice')], default='class_feat', help_text='Does this belong to the base class, a subclass, or is it a subclass-choice?', max_length=20)),
                ('kind', models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table')], default='class_feat', help_text='What *type* of feature this is.', max_length=20)),
                ('modify_proficiency_target', models.CharField(blank=True, choices=[('armor', 'Armor'), ('dodge', 'Dodge'), ('perception', 'Perception'), ('initiative', 'Initiative'), ('dc', 'Spell/DC'), ('reflex', 'Reflex Save'), ('fortitude', 'Fortitude Save'), ('will', 'Will Save'), ('weapon', 'Weapon')], help_text='Which proficiency to modify', max_length=20)),
                ('cantrips_formula', models.CharField(blank=True, help_text="Formula for number of cantrips known per class level, e.g. '1 + level//4'", max_length=100)),
                ('spells_known_formula', models.CharField(blank=True, help_text="Formula for number of spells known per class level, e.g. '2 + level//2'", max_length=100)),
                ('spells_prepared_formula', models.CharField(blank=True, help_text="Formula for number of spells you can prepare per class level, e.g. 'intelligence//2 + level//3'", max_length=100)),
                ('action_type', models.CharField(blank=True, choices=[('action_1', 'One Action'), ('action_2', 'Two Actions'), ('action_3', 'Three Actions'), ('reaction', 'Reaction'), ('free', 'Free Action')], help_text='What kind of action this ability consumes.', max_length=10, null=True, verbose_name='Action Required')),
                ('activity_type', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], default='active', help_text='For class_trait & subclass_choice: active consumes uses; passive is static.', max_length=7)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('has_options', models.BooleanField(default=False, help_text='If checked, you must add at least one Option below.')),
                ('formula', models.CharField(blank=True, help_text="Any dice+attribute expression, e.g. '1d10+level'", max_length=100)),
                ('uses', models.CharField(blank=True, help_text="How many times? e.g. 'level', '1', 'level/3 round down +1'", max_length=100)),
                ('formula_target', models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('constitution', 'Constitution'), ('charisma', 'Charisma'), ('acrobatics', 'Acrobatics (DEX)'), ('animal_handling', 'Animal Handling (WIS)'), ('arcana', 'Arcana (INT)'), ('arts', 'Arts (CHA)'), ('athletics', 'Athletics (STR)'), ('charm', 'Charm (CHA)'), ('deception', 'Deception (CHA)'), ('insight', 'Insight (WIS/CHA)'), ('investigation', 'Investigation (INT)'), ('linguistic', 'Linguistic (INT)'), ('local_instinct', 'Local Instinct (WIS)'), ('general_knowledge', 'General Knowledge (INT)'), ('lore', 'Lore (INT)'), ('memory', 'Memory (INT)'), ('sleight_of_hand', 'Sleight of Hand (DEX)'), ('stealth', 'Stealth (DEX)'), ('survival', 'Survival (WIS)'), ('technology', 'Technology (INT)'), ('attack_roll', 'Attack Roll'), ('damage', 'Damage'), ('save_dc', 'Save DC'), ('reflex_save', 'Reflex Save'), ('fortitude_save', 'Fortitude Save'), ('will_save', 'Will Save'), ('initiative', 'Initiative'), ('skill_check', 'Skill Check'), ('temp_HP', 'Temporary Hitpoints'), ('HP', 'Hitpoints'), ('attack', 'Attack Roll'), ('weapon_attack', 'Weapon Attack'), ('melee_attack', 'Melee Attack'), ('ranged_attack', 'Ranged Attack'), ('melee_weapon_attack', 'Melee Weapon Attack'), ('ranged_weapon_attack', 'Ranged Weapon Attack'), ('unarmed_attack', 'Unarmed Attack'), ('spell_attack', 'Spell Attack'), ('spell_damage', 'Spell Damage'), ('weapon_damage', 'Weapon Damage'), ('melee_weapon_damage', 'Melee Weapon Damage'), ('melee_damage', 'Melee Damage'), ('ranged_damage', 'Ranged Weapon Damage'), ('ranged_attack', 'Ranged Attack'), ('unarmed_damage', 'Unarmed Damage')], default=None, help_text='What kind of roll this formula is used for (optional)', max_length=20, null=True)),
                ('character_class', models.ForeignKey(blank=True, help_text='Which class grants this feature?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='characters.characterclass')),
            ],
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='characters.characterclass')),
            ],
            options={
                'ordering': ['character_class', 'level'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_option', models.CharField(blank=True, help_text='One of the parent feature’s option labels', max_length=100)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.classlevel')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.classfeature')),
            ],
            options={
                'unique_together': {('class_level', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='classlevel',
            name='features',
            field=models.ManyToManyField(help_text='All ClassFeatures (and option‑selections) you get at this level', through='characters.ClassLevelFeature', to='characters.classfeature'),
        ),
        migrations.CreateModel(
            name='ClassSubclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, help_text='Optional shorthand code for this subclass', max_length=20)),
                ('modular_rules', models.JSONField(blank=True, help_text='Extra numbers for modular systems.  eg. {"modules_per_mastery":2, "ability_req":{"0":13,"1":15}}', null=True)),
                ('base_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='characters.characterclass')),
            ],
        ),
        migrations.AddField(
            model_name='classfeature',
            name='subclasses',
            field=models.ManyToManyField(blank=True, help_text='For subclass_feat, which subclasses receive this?', related_name='features', to='characters.classsubclass'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='High‑level archetype tags (e.g. Martial, Spellcaster…)', related_name='classes', to='characters.classtag'),
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='characters.classfeature')),
                ('grants_feature', models.ForeignKey(blank=True, help_text='Which other feature does this choice grant?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_by_options', to='characters.classfeature')),
            ],
        ),
        migrations.AddField(
            model_name='classfeature',
            name='modify_proficiency_amount',
            field=models.ForeignKey(blank=True, help_text='Pick the exact proficiency tier to grant (overrides current tier)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.proficiencytier'),
        ),
        migrations.CreateModel(
            name='SubclassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('linear', 'Linear (fixed level)'), ('modular_linear', 'Modular Linear (tiered)'), ('modular_mastery', 'Modular Mastery (pick & master)')], default='linear', max_length=20)),
                ('modular_rules', models.JSONField(blank=True, help_text='Extra numbers for modular systems (e.g. {modules_per_mastery:2, max_mastery_3:1})', null=True)),
                ('name', models.CharField(help_text='Umbrella / Order name (e.g. Moon Circle)', max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclass_groups', to='characters.characterclass')),
            ],
            options={
                'ordering': ['character_class', 'name'],
                'unique_together': {('character_class', 'name')},
            },
        ),
        migrations.AddField(
            model_name='classsubclass',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Which umbrella / order this belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='characters.subclassgroup'),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='subclass_group',
            field=models.ForeignKey(blank=True, help_text='For a subclass_choice, pick the umbrella shown to the player.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_features', to='characters.subclassgroup'),
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifier, e.g. 'wood_elf'", max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='characters.race')),
            ],
            options={
                'unique_together': {('race', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('half_elf_origin', models.CharField(blank=True, max_length=20)),
                ('bg_combo', models.CharField(blank=True, max_length=10)),
                ('main_background', models.CharField(blank=True, max_length=50)),
                ('side_background_1', models.CharField(blank=True, max_length=50)),
                ('side_background_2', models.CharField(blank=True, max_length=50)),
                ('HP', models.IntegerField(blank=True, null=True)),
                ('temp_HP', models.IntegerField(blank=True, null=True)),
                ('strength', models.IntegerField(default=8)),
                ('dexterity', models.IntegerField(default=8)),
                ('constitution', models.IntegerField(default=8)),
                ('intelligence', models.IntegerField(default=8)),
                ('wisdom', models.IntegerField(default=8)),
                ('charisma', models.IntegerField(default=8)),
                ('level', models.PositiveIntegerField(default=0)),
                ('backstory', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='characters.race')),
                ('subrace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='characters.subrace')),
            ],
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subskills', to='characters.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_progress', to='characters.character')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.characterclass')),
            ],
            options={
                'unique_together': {('character', 'character_class')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('character_class', 'level')},
        ),
        migrations.CreateModel(
            name='ClassProficiencyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_type', models.CharField(choices=[('armor', 'Armor'), ('dodge', 'Dodge'), ('perception', 'Perception'), ('initiative', 'Initiative'), ('dc', 'Spell/DC'), ('reflex', 'Reflex Save'), ('fortitude', 'Fortitude Save'), ('will', 'Will Save'), ('weapon', 'Weapon')], max_length=20)),
                ('at_level', models.PositiveIntegerField(help_text='Level at which this tier becomes active')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_progress', to='characters.characterclass')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.proficiencytier')),
            ],
            options={
                'ordering': ['character_class', 'proficiency_type', 'at_level'],
                'unique_together': {('character_class', 'proficiency_type', 'at_level')},
            },
        ),
        migrations.CreateModel(
            name='ClassResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(blank=True, help_text="Formula for how many points this class grants at a given level, e.g. 'ceil(level/2) + strength_modifier', or 'floor(level/3)+1', etc.", max_length=100)),
                ('max_points', models.IntegerField(default=0, help_text='Maximum pool size (0 = no cap)')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='characters.characterclass')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.resourcetype')),
            ],
            options={
                'unique_together': {('character_class', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='CharacterResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='characters.character')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.resourcetype')),
            ],
            options={
                'unique_together': {('character', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='SpellSlotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10'), (11, 'Level 11'), (12, 'Level 12'), (13, 'Level 13'), (14, 'Level 14'), (15, 'Level 15'), (16, 'Level 16'), (17, 'Level 17'), (18, 'Level 18'), (19, 'Level 19'), (20, 'Level 20')], help_text='Character level')),
                ('slot1', models.PositiveSmallIntegerField(default=0, help_text='1st-rank slots')),
                ('slot2', models.PositiveSmallIntegerField(default=0, help_text='2nd-rank slots')),
                ('slot3', models.PositiveSmallIntegerField(default=0, help_text='3rd-rank slots')),
                ('slot4', models.PositiveSmallIntegerField(default=0, help_text='4th-rank slots')),
                ('slot5', models.PositiveSmallIntegerField(default=0, help_text='5th-rank slots')),
                ('slot6', models.PositiveSmallIntegerField(default=0, help_text='6th-rank slots')),
                ('slot7', models.PositiveSmallIntegerField(default=0, help_text='7th-rank slots')),
                ('slot8', models.PositiveSmallIntegerField(default=0, help_text='8th-rank slots')),
                ('slot9', models.PositiveSmallIntegerField(default=0, help_text='9th-rank slots')),
                ('slot10', models.PositiveSmallIntegerField(default=0, help_text='10th-rank slots')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_slot_rows', to='characters.classfeature')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('feature', 'level')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classsubclass',
            unique_together={('base_class', 'name')},
        ),
        migrations.CreateModel(
            name='RacialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('saving_throw_required', models.BooleanField(default=False)),
                ('saving_throw_type', models.CharField(blank=True, choices=[('reflex', 'Reflex'), ('fortitude', 'Fortitude'), ('will', 'Will')], max_length=10, null=True)),
                ('damage_type', models.CharField(blank=True, choices=[('physical_bludgeoning', 'Physical Bludgeoning'), ('physical_slashing', 'Physical Slashing'), ('physical_piercing', 'Physical Piercing'), ('explosive', 'Explosive'), ('magical_bludgeoning', 'Magical Bludgeoning'), ('magical_slashing', 'Magical Slashing'), ('magical_piercing', 'Magical Piercing'), ('acid', 'Acid'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('thunder', 'Thunder'), ('true', 'True')], max_length=25, null=True)),
                ('formula', models.CharField(blank=True, max_length=100)),
                ('uses', models.CharField(blank=True, max_length=100)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='characters.race')),
                ('subrace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='characters.subrace')),
            ],
            options={
                'unique_together': {('race', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSkillProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='characters.character')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.proficiencylevel')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.subskill')),
            ],
            options={
                'unique_together': {('character', 'subskill')},
            },
        ),
    ]
