# Generated by Django 5.1.6 on 2025-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulebookpage',
            options={'ordering': ['rulebook__name', 'order']},
        ),
        migrations.AddField(
            model_name='rulebook',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rulebook_images/'),
        ),
        migrations.AddField(
            model_name='rulebookpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rulebook_page_images/'),
        ),
        migrations.AlterField(
            model_name='rulebookpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rulebookpage',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
