# Generated by Django 5.1.6 on 2025-04-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='background',
        ),
        migrations.AddField(
            model_name='character',
            name='bg_combo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='half_elf_origin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='main_background',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='side_background_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='side_background_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_proficiencies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='character',
            name='subrace',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=8),
        ),
    ]
