# Generated by Django 5.1.6 on 2025-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='selection_mode',
        ),
        migrations.AddField(
            model_name='background',
            name='primary_selection_mode',
            field=models.CharField(choices=[('all', 'Grant all SubSkills'), ('pick_one', 'Let user pick exactly one SubSkill')], default='all', help_text='If primary_selection is a Skill with sub-skills, do you grant all of them or let the player choose one?', max_length=10),
        ),
        migrations.AddField(
            model_name='background',
            name='secondary_selection_mode',
            field=models.CharField(choices=[('all', 'Grant all SubSkills'), ('pick_one', 'Let user pick exactly one SubSkill')], default='all', help_text='Same, but for the secondary selection.', max_length=10),
        ),
    ]
