# Generated by Django 5.1.6 on 2025-04-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_background_character_bg_combo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProficiencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tier', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ability', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='skill_proficiencies',
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subskills', to='characters.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkillProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='characters.character')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.proficiencylevel')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.subskill')),
            ],
            options={
                'unique_together': {('character', 'subskill')},
            },
        ),
    ]
