# Generated by Django 5.1.6 on 2025-06-15 16:32

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_rulebookpage_options_rulebook_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoremasterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='loremaster/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoremasterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for list page')),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='loremaster/covers/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='loremaster/main/')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ManyToManyField(blank=True, related_name='articles', to='characters.loremasterimage')),
            ],
            options={
                'verbose_name': 'Loremaster Article',
                'verbose_name_plural': 'Loremaster Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
