# Generated by Django 5.1.6 on 2025-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_skill_selection_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='primary_selection_mode',
            field=models.CharField(choices=[('all', 'Grant all SubSkills'), ('pick_one', 'Let user pick exactly one SubSkill'), ('pick_two', 'Let user pick exactly two SubSkill'), ('pick_three', 'Let user pick exactly three SubSkill')], default='all', help_text='If primary_selection is a Skill with sub-skills, do you grant all of them or let the player choose one?', max_length=10),
        ),
        migrations.AlterField(
            model_name='background',
            name='secondary_selection_mode',
            field=models.CharField(choices=[('all', 'Grant all SubSkills'), ('pick_one', 'Let user pick exactly one SubSkill'), ('pick_two', 'Let user pick exactly two SubSkill'), ('pick_three', 'Let user pick exactly three SubSkill')], default='all', help_text='Same, but for the secondary selection.', max_length=10),
        ),
    ]
