# Generated by Django 5.1.6 on 2025-05-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_racetag_alter_racialfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevelfeature',
            name='chosen_option',
        ),
    ]
