# Generated by Django 5.1.6 on 2025-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_background_primary_selection_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='bonus_budget',
            field=models.PositiveSmallIntegerField(default=4, help_text='Total points (fixed + free) this race may grant to ability scores.'),
        ),
        migrations.AddField(
            model_name='race',
            name='free_points',
            field=models.PositiveSmallIntegerField(default=0, help_text='Of the bonus_budget, how many are unassigned and left for the player to allocate.'),
        ),
        migrations.AddField(
            model_name='race',
            name='max_bonus_per_ability',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum total bonus (fixed + free) any one ability may receive.'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='bonus_budget',
            field=models.PositiveSmallIntegerField(default=4, help_text='Total points (fixed + free) this race may grant to ability scores.'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='free_points',
            field=models.PositiveSmallIntegerField(default=0, help_text='Of the bonus_budget, how many are unassigned and left for the player to allocate.'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='max_bonus_per_ability',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum total bonus (fixed + free) any one ability may receive.'),
        ),
    ]
