# Generated by Django 5.1.6 on 2025-05-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_classlevelfeature_chosen_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Pick which pre-defined racial features apply to this race', related_name='races', to='characters.racialfeature'),
        ),
        migrations.AlterField(
            model_name='racialfeature',
            name='race',
            field=models.ForeignKey(help_text='Which Race grants this feature?', on_delete=django.db.models.deletion.CASCADE, related_name='racial_features', to='characters.race'),
        ),
        migrations.AlterField(
            model_name='racialfeature',
            name='subrace',
            field=models.ForeignKey(blank=True, help_text='(Optional) only this Subrace gets it', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subrace_racial_features', to='characters.subrace'),
        ),
    ]
