# Generated by Django 5.1.6 on 2025-04-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_proficiencylevel_skillcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_progress', to='characters.character')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.characterclass')),
            ],
            options={
                'unique_together': {('character', 'character_class')},
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('proficiency_tier', models.CharField(max_length=50)),
                ('features', models.JSONField(default=list)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='characters.characterclass')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('character_class', 'level')},
            },
        ),
    ]
