# Generated by Django 5.1.6 on 2025-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20250616_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Describe what this skill covers'),
        ),
        migrations.AddField(
            model_name='subskill',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detail for this sub-skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default='strength', help_text='Which ability governs this skill', max_length=12),
        ),
    ]
