# Generated by Django 5.1.6 on 2025-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_race_bonus_budget_race_free_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifier, e.g. ‘common’, ‘elvish’', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Human-readable name, e.g. ‘Common’', max_length=100)),
                ('script', models.CharField(blank=True, help_text='Optional script name, e.g. ‘Elvish Runes’', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Select which languages this race knows inherently', to='characters.language'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Select which languages this race knows inherently', to='characters.language'),
        ),
    ]
