# Generated by Django 5.1.6 on 2025-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_race_features_alter_racialfeature_race_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='characterclass',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Upload the main portrait or icon for this class.', null=True, upload_to='class_images/primary/'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Upload a second image (e.g. a symbol or alternate art) for this class.', null=True, upload_to='class_images/secondary/'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='tertiary_image',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail or list‐page image for this class.', null=True, upload_to='class_images/tertiary/'),
        ),
        migrations.AddField(
            model_name='race',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Upload the main portrait or icon for this race.', null=True, upload_to='race_images/primary/'),
        ),
        migrations.AddField(
            model_name='race',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Upload a second image (e.g. a banner or alternate art) for this race.', null=True, upload_to='race_images/secondary/'),
        ),
        migrations.AddField(
            model_name='race',
            name='tertiary_image',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail or list‐page image for this race.', null=True, upload_to='race_images/tertiary/'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Upload the main portrait or icon for this race.', null=True, upload_to='race_images/primary/'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Upload a second image (e.g. a banner or alternate art) for this race.', null=True, upload_to='race_images/secondary/'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='tertiary_image',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail or list‐page image for this race.', null=True, upload_to='race_images/tertiary/'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='key_abilities',
            field=models.ManyToManyField(help_text='Select exactly one or two key ability scores for this class.', to='characters.abilityscore'),
        ),
    ]
