# Generated by Django 5.1.6 on 2025-05-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_abilityscore_characterclass_primary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclassgroup',
            name='code',
            field=models.CharField(blank=True, help_text='Optional shorthand code', max_length=20),
        ),
        migrations.AlterField(
            model_name='subclassgroup',
            name='modular_rules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subclassgroup',
            name='name',
            field=models.CharField(help_text="Umbrella/Order name (e.g. 'Moon Circle')", max_length=100),
        ),
        migrations.CreateModel(
            name='SubclassTierLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField(help_text='Tier index (e.g. 1, 2, 3).')),
                ('at_level', models.PositiveIntegerField(help_text='Which ClassLevel.level unlocks this tier.')),
                ('subclass_group', models.ForeignKey(help_text='Which modular-linear group this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tier_levels', to='characters.subclassgroup')),
            ],
            options={
                'ordering': ['subclass_group', 'tier'],
                'unique_together': {('subclass_group', 'at_level'), ('subclass_group', 'tier')},
            },
        ),
    ]
