# Generated by Django 5.1.6 on 2025-04-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_classfeature_proficiencytier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeature',
            name='option_labels',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='formula',
            field=models.CharField(blank=True, help_text="Any dice+attribute expression, e.g. '1d10+level', 'proficiency_modifier/2 (round up)'", max_length=100),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='uses',
            field=models.CharField(blank=True, help_text="How many times can this be used?  Either a fixed integer or expression, e.g. 'level', '1', 'proficiency_modifier', 'level/3 round down +1'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='has_options',
            field=models.BooleanField(default=False, help_text='If checked, you must add at least one Option below.'),
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='characters.classfeature')),
            ],
        ),
    ]
