# Generated by Django 5.1.6 on 2025-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_language_race_languages_subrace_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='script',
        ),
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of this language (dialects, notes, etc.)'),
        ),
    ]
