# Generated by Django 5.1.6 on 2025-05-31 19:23

# characters/migrations/0007_drop_at_level_constraint.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0006_alter_subclassgroup_code_and_more"),
    ]

    operations = [
        # 1) Shrink the unique_together down to only (subclass_group, tier).
        migrations.AlterUniqueTogether(
            name="subclasstierlevel",
            unique_together={("subclass_group", "tier")},
        ),
        # 2) Now that the constraint referring to at_level is gone, drop at_level itself.
        migrations.RemoveField(
            model_name="subclasstierlevel",
            name="at_level",
        ),
    ]
