# Generated by Django 5.1.6 on 2025-07-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_language_script_language_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='side_background_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='side_background_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
