# Generated by Django 5.1.6 on 2025-06-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20250616_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subskill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subskill',
            name='skill',
            field=models.ForeignKey(help_text='Which Skill this SubSkill falls under', on_delete=django.db.models.deletion.CASCADE, related_name='subskills', to='characters.skill'),
        ),
    ]
