# Generated by Django 5.1.6 on 2025-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_classfeature_option_labels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='class_ID',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='hit_die',
            field=models.PositiveSmallIntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')], default=8, help_text='Your class’s Hit Die'),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='formula',
            field=models.CharField(blank=True, help_text="Dice/attribute expression, e.g. '1d10+level', 'prof_mod/2 round up'", max_length=100),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='uses',
            field=models.CharField(blank=True, help_text="Number of uses or expression, e.g. 'level', '1', 'prof_mod', 'level/3 round down +1'", max_length=100),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='features',
            field=models.ManyToManyField(help_text='All ClassFeatures (and option‑selections) you get at this level', through='characters.ClassLevelFeature', to='characters.classfeature'),
        ),
        migrations.AlterField(
            model_name='classlevelfeature',
            name='chosen_option',
            field=models.CharField(blank=True, help_text='One of the parent feature’s option labels', max_length=100),
        ),
        migrations.AlterField(
            model_name='classproficiencyprogress',
            name='at_level',
            field=models.PositiveIntegerField(help_text='Level at which this tier becomes active'),
        ),
    ]
