# Generated by Django 5.1.6 on 2025-04-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_character_character_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='character_class',
            field=models.ForeignKey(blank=True, help_text='Which class grants this feature?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='characters.characterclass'),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='formula',
            field=models.CharField(blank=True, help_text="Any dice+attribute expression, e.g. '1d10+level'", max_length=100),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='uses',
            field=models.CharField(blank=True, help_text="How many times? e.g. 'level', '1', 'level/3 round down +1'", max_length=100),
        ),
    ]
