# Generated by Django 5.1.6 on 2025-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_subskill_description_alter_subskill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='secondary_ability',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], help_text='Optional secondary governing ability', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default='strength', help_text='Primary governing ability', max_length=12),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_advanced',
            field=models.BooleanField(default=False),
        ),
    ]
