# Generated by Django 5.1.6 on 2025-07-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_character_side_background_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='half_elf_origin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
