# Generated by Django 5.1.6 on 2025-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_classfeature_character_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='HP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='temp_HP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
