# Generated by Django 5.1.6 on 2025-06-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_skill_secondary_ability_alter_skill_ability_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterskillproficiency',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='charactersubskillproficiency',
            unique_together={('character', 'selected_skill_type', 'selected_skill_id')},
        ),
        migrations.AddField(
            model_name='characterskillproficiency',
            name='selected_skill_id',
            field=models.PositiveIntegerField(blank=True, help_text='(temporarily nullable so migrations can run; remove null=True once back-filled)', null=True, verbose_name='Skill or SubSkill ID'),
        ),
        migrations.AddField(
            model_name='characterskillproficiency',
            name='selected_skill_type',
            field=models.ForeignKey(blank=True, help_text='(temporarily nullable so migrations can run; remove null=True once back-filled)', limit_choices_to=models.Q(('app_label', 'characters'), ('model__in', ['skill', 'subskill'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Skill or SubSkill type'),
        ),
        migrations.AddField(
            model_name='charactersubskillproficiency',
            name='selected_skill_id',
            field=models.PositiveIntegerField(blank=True, help_text='(temporarily nullable so migrations can run; you can remove null=True once it’s back-filled)', null=True, verbose_name='Skill or SubSkill ID'),
        ),
        migrations.AddField(
            model_name='charactersubskillproficiency',
            name='selected_skill_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'characters'), ('model__in', ['skill', 'subskill'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Skill or SubSkill type'),
        ),
        migrations.RemoveField(
            model_name='characterskillproficiency',
            name='subskill',
        ),
        migrations.RemoveField(
            model_name='charactersubskillproficiency',
            name='subskill',
        ),
    ]
