# Generated by Django 5.1.6 on 2025-05-31 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_subclasstierlevel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasstierlevel',
            name='subclass_group',
            field=models.ForeignKey(help_text='Which group this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tier_levels', to='characters.subclassgroup'),
        ),
        migrations.AlterField(
            model_name='subclasstierlevel',
            name='tier',
            field=models.PositiveIntegerField(help_text='Tier index (e.g. 1, 2, 3, …).  Must match the integer suffix on feature.code.'),
        ),
    ]
