# Generated by Django 5.1.6 on 2025-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_half_elf_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='modify_proficiency_target',
            field=models.CharField(blank=True, help_text='Which proficiency to modify', max_length=50),
        ),
    ]
