# Generated by Django 5.1.6 on 2025-04-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_hp_character_temp_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureoption',
            name='grants_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_by_options', to='characters.classfeature'),
        ),
    ]
