# Generated by Django 5.1.6 on 2025-06-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_characterskillproficiency_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterskillproficiency',
            options={'verbose_name': 'Character Skill Proficiency', 'verbose_name_plural': 'Character Skill Proficiencies'},
        ),
        migrations.AlterField(
            model_name='characterskillproficiency',
            name='selected_skill_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Skill or SubSkill ID'),
        ),
        migrations.AlterField(
            model_name='characterskillproficiency',
            name='selected_skill_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'characters'), ('model__in', ['skill', 'subskill'])), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Skill or SubSkill type'),
        ),
        migrations.AlterUniqueTogether(
            name='characterskillproficiency',
            unique_together={('character', 'selected_skill_type', 'selected_skill_id')},
        ),
    ]
