# Generated by Django 5.1.6 on 2025-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_classfeature_modify_proficiency_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='starting_hp',
            field=models.IntegerField(blank=True, help_text='Starting HP for this race (to be filled in)', null=True),
        ),
        migrations.AddField(
            model_name='subrace',
            name='starting_hp',
            field=models.IntegerField(blank=True, help_text='Starting HP for this race (to be filled in)', null=True),
        ),
    ]
