# Generated by Django 5.1.6 on 2025-04-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_featureoption_grants_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureoption',
            name='grants_feature',
            field=models.ForeignKey(blank=True, help_text='Which other feature does this choice grant?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_by_options', to='characters.classfeature'),
        ),
    ]
