# Generated by Django 5.1.6 on 2025-07-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_race_starting_hp_subrace_starting_hp'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='gain_resistance_amount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Flat reduction amount (only for ‘reduction’ mode).', null=True),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='gain_resistance_mode',
            field=models.CharField(blank=True, choices=[('resistance', 'Resistance (half damage)'), ('reduction', 'Damage Reduction (flat)')], help_text='Resistance vs. Damage Reduction?', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='gain_resistance_types',
            field=models.JSONField(blank=True, help_text='List of damage types to which this feature applies.', null=True),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='kind',
            field=models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table'), ('inherent_spell', 'Inherent Spell'), ('gain_proficiency', 'Gain Proficiency'), ('gain_resistance', 'Gain Resistance')], default='class_feat', help_text='What *type* of feature this is.', max_length=20),
        ),
        migrations.CreateModel(
            name='DamageResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('damage_type', models.CharField(choices=[('all', 'All Damage Types'), ('physical_all', 'All Physical Damage'), ('physical_non_magical', 'Non-magical Physical Damage'), ('physical_bludgeoning', 'Physical Bludgeoning'), ('physical_slashing', 'Physical Slashing'), ('physical_piercing', 'Physical Piercing'), ('explosive', 'Explosive'), ('magical_bludgeoning', 'Magical Bludgeoning'), ('magical_slashing', 'Magical Slashing'), ('magical_piercing', 'Magical Piercing'), ('acid', 'Acid'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('thunder', 'Thunder'), ('true', 'True')], help_text='Which damage type (or grouping) this resistance applies to.', max_length=25)),
                ('amount', models.PositiveSmallIntegerField(default=0, help_text='How much to subtract from incoming damage of that type.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'damage_type')},
            },
        ),
    ]
