# Generated by Django 5.1.6 on 2025-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_alter_characterskillproficiency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='description',
            field=models.TextField(blank=True, help_text='Background Summary:', null=True),
        ),
    ]
