# Generated by Django 5.1.6 on 2025-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_classfeature_mastery_rank_classfeature_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='level_required',
            field=models.PositiveIntegerField(blank=True, help_text='(Only for subclass_feats) The minimum class‐level at which this feature is actually gained.', null=True),
        ),
    ]
