# Generated by Django 5.1.6 on 2025-06-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_background_description'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='primary_skill',
        ),
        migrations.RemoveField(
            model_name='background',
            name='secondary_skill',
        ),
        migrations.AddField(
            model_name='background',
            name='primary_skill_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Primary Skill/SubSkill ID'),
        ),
        migrations.AddField(
            model_name='background',
            name='primary_skill_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'characters'), ('model__in', ['skill', 'subskill'])), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='background',
            name='secondary_skill_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Secondary Skill/SubSkill ID'),
        ),
        migrations.AddField(
            model_name='background',
            name='secondary_skill_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'characters'), ('model__in', ['skill', 'subskill'])), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
