# Generated by Django 5.1.6 on 2025-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_alter_featureoption_grants_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='formula_target',
            field=models.CharField(choices=[('acrobatics', 'Acrobatics (DEX)'), ('animal_handling', 'Animal Handling (WIS)'), ('arcana', 'Arcana (INT)'), ('arts', 'Arts (CHA)'), ('athletics', 'Athletics (STR)'), ('charm', 'Charm (CHA)'), ('deception', 'Deception (CHA)'), ('insight', 'Insight (WIS/CHA)'), ('investigation', 'Investigation (INT)'), ('linguistic', 'Linguistic (INT)'), ('local_instinct', 'Local Instinct (WIS)'), ('general_knowledge', 'General Knowledge (INT)'), ('lore', 'Lore (INT)'), ('memory', 'Memory (INT)'), ('sleight_of_hand', 'Sleight of Hand (DEX)'), ('stealth', 'Stealth (DEX)'), ('survival', 'Survival (WIS)'), ('technology', 'Technology (INT)'), ('attack_roll', 'Attack Roll'), ('damage', 'Damage'), ('save_dc', 'Save DC'), ('reflex_save', 'Reflex Save'), ('fortitude_save', 'Fortitude Save'), ('will_save', 'Will Save'), ('initiative', 'Initiative'), ('skill_check', 'Skill Check'), ('attack', 'Attack Roll'), ('weapon_attack', 'Weapon Attack'), ('melee_attack', 'Melee Attack'), ('ranged_attack', 'Ranged Attack'), ('melee_weapon_attack', 'Melee Weapon Attack'), ('ranged_weapon_attack', 'Ranged Weapon Attack'), ('unarmed_attack', 'Unarmed Attack'), ('spell_attack', 'Spell Attack'), ('spell_damage', 'Spell Damage'), ('weapon_damage', 'Weapon Damage'), ('melee_weapon_damage', 'Melee Weapon Damage'), ('melee_damage', 'Melee Damage'), ('ranged_damage', 'Ranged Weapon Damage'), ('ranged_attack', 'Ranged Attack'), ('unarmed_damage', 'Unarmed Damage')], default='attack_roll', help_text='What kind of roll this formula is used for', max_length=20),
        ),
    ]
