# Generated by Django 5.1.6 on 2025-06-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_classfeature_level_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='scope',
            field=models.CharField(choices=[('class_feat', 'Class Feature'), ('subclass_feat', 'Subclass Feature'), ('subclass_choice', 'Subclass Choice'), ('gain_subclass_feat', 'Gain Subclass Feature')], default='class_feat', help_text='Does this belong to the base class, a subclass, or is it a subclass-choice?', max_length=20),
        ),
    ]
