# Generated by Django 5.1.6 on 2025-07-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_classfeature_gain_resistance_amount_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialItemTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='traits',
        ),
        migrations.AddField(
            model_name='weapon',
            name='range_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum range', null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='range_normal',
            field=models.PositiveIntegerField(blank=True, help_text='Normal range for ranged weapons', null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='range_type',
            field=models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], default='melee', max_length=6),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='gain_resistance_types',
            field=models.JSONField(blank=True, default=list, help_text='List of damage types to which this feature applies.'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('armor_value', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('clothing', 'Clothing'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('shield', 'Shield')], max_length=10)),
                ('speed_penalty', models.IntegerField(help_text='Flat penalty to speed (ft)')),
                ('hinderance', models.IntegerField(help_text='Penalty to Str/Dex checks')),
                ('traits', models.ManyToManyField(blank=True, help_text='Select any special traits', to='characters.armortrait')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('very_rare', 'Very Rare'), ('legendary', 'Legendary')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.equipmentslot')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialItemTraitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Active vs Passive')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_values', to='characters.specialitem')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.specialitemtrait')),
            ],
        ),
    ]
