# Generated by Django 5.1.6 on 2025-07-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_armortrait_equipmentslot_specialitemtrait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='specialitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='specialitem',
            name='attunement',
            field=models.BooleanField(default=False, verbose_name='Attunement required'),
        ),
        migrations.AddField(
            model_name='specialitem',
            name='weapon',
            field=models.ForeignKey(blank=True, help_text='If this is a magical weapon, pick the base Weapon here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.weapon'),
        ),
    ]
