# Generated by Django 5.1.6 on 2025-04-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_classfeature_formula_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='feat_type',
            field=models.CharField(choices=[('class', 'Class feat'), ('skill', 'Skill feat')], default='class', help_text='Is this a class‑feat or a skill‑feat?', max_length=10),
        ),
    ]
