# Generated by Django 5.1.6 on 2025-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_skill_weapon_weapontrait_weapontraitvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalLevelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='Character level (e.g. 1, 2, 3 …).', unique=True)),
                ('grants_general_feat', models.BooleanField(default=False, help_text='If True, then at this level every class gains a General Feat.')),
                ('grants_asi', models.BooleanField(default=False, help_text='If True, then at this level every class gains an ASI.')),
            ],
            options={
                'verbose_name': 'Universal Level Feature',
                'verbose_name_plural': 'Universal Level Features',
                'ordering': ['level'],
            },
        ),
    ]
