# Generated by Django 5.1.6 on 2025-04-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_classfeature_feat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='feat_type',
            field=models.CharField(choices=[('Class Trait', 'Class Trait'), ('class', 'Class feat'), ('skill', 'Skill feat')], default='class', help_text='Is this a class‑feat or a skill‑feat?', max_length=100),
        ),
    ]
