# Generated by Django 5.1.6 on 2025-07-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_remove_specialitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialitemtraitvalue',
            options={'verbose_name': 'Item Trait', 'verbose_name_plural': 'Item Traits'},
        ),
        migrations.RemoveField(
            model_name='specialitemtrait',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specialitemtraitvalue',
            name='item',
        ),
        migrations.AddField(
            model_name='specialitem',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.armor'),
        ),
        migrations.AddField(
            model_name='specialitem',
            name='enhancement_bonus',
            field=models.IntegerField(blank=True, help_text='Enchantment bonus (e.g. +1)', null=True),
        ),
        migrations.AddField(
            model_name='specialitem',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('wearable', 'Wearable'), ('artifact', 'Artifact'), ('consumable', 'Consumable')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='action_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='damage_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='description',
            field=models.TextField(blank=True, verbose_name='Trait description'),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='formula_target',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='modify_proficiency_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='modify_proficiency_target',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_basic_failure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_basic_success',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_critical_failure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_critical_success',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_failure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_granularity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_success',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='saving_throw_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='special_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.specialitem'),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='uses',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.weapon'),
        ),
        migrations.AlterField(
            model_name='specialitemtrait',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
