# Generated by Django 5.1.6 on 2025-07-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_alter_specialitemtraitvalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='specialitem',
            name='enhancement_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialitem',
            name='wearable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.wearableslot'),
        ),
    ]
