# Generated by Django 5.1.6 on 2025-06-08 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_universallevelfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='Character level when gained')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='characters.character')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.classfeature')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.featureoption')),
                ('racial_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.racialfeature')),
                ('subclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.classsubclass')),
            ],
            options={
                'unique_together': {('character', 'feature', 'option', 'subclass', 'level')},
            },
        ),
    ]
