# Generated by Django 5.1.6 on 2025-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_wearableslot_alter_specialitem_enhancement_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitemtraitvalue',
            name='trait',
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Trait name'),
        ),
        migrations.DeleteModel(
            name='SpecialItemTrait',
        ),
    ]
