# Generated by Django 5.1.6 on 2025-06-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_characterfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('primary_bonus', models.PositiveSmallIntegerField()),
                ('secondary_bonus', models.PositiveSmallIntegerField()),
                ('primary_ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='characters.abilityscore')),
                ('primary_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='characters.subskill')),
                ('secondary_ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='characters.abilityscore')),
                ('secondary_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='characters.subskill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
