# Generated by Django 5.1.6 on 2025-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_classtag_alter_classfeature_feat_type_classsubclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='subclasses',
            field=models.ManyToManyField(blank=True, help_text='Which subclass(es) gain this feature?', to='characters.classsubclass'),
        ),
    ]
