# Generated by Django 5.1.6 on 2025-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='features',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='spell_list',
            field=models.CharField(blank=True, choices=[('arcane', 'Arcane'), ('primal', 'Primal'), ('occult', 'Occult'), ('divine', 'Divine')], help_text='Which tradition’s slots these are (Arcane/Primal/Occult/Divine).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='racialfeature',
            name='kind',
            field=models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table'), ('inherent_spell', 'Inherent Spell'), ('inherent_spell', 'Inherent Spell')], default='inherent_spell', help_text='What *type* of feature this is.', max_length=20),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='kind',
            field=models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table'), ('inherent_spell', 'Inherent Spell')], default='class_feat', help_text='What *type* of feature this is.', max_length=20),
        ),
    ]
