# Generated by Django 5.1.6 on 2025-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_remove_specialitemtraitvalue_trait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_amount',
        ),
        migrations.RemoveField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_types',
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_mode',
            field=models.CharField(blank=True, choices=[('resistance', 'Resistance (half damage)'), ('reduction', 'Damage Reduction (flat)')], help_text='Resistance vs. Damage Reduction?', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_granularity',
            field=models.CharField(blank=True, choices=[('basic', 'Basic (Success / Failure)'), ('normal', 'Normal (Crit / Success / Failure / Crit Failure)')], help_text='Simple or full save table?', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_type',
            field=models.CharField(blank=True, choices=[('reflex', 'Reflex'), ('fortitude', 'Fortitude'), ('will', 'Will')], help_text='Which saving throw?', max_length=50),
        ),
    ]
