# Generated by Django 5.1.6 on 2025-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_alter_classfeature_subclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubclass',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
