# Generated by Django 5.1.6 on 2025-08-01 17:25

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_remove_specialitemtraitvalue_gain_resistance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
