# Generated by Django 5.1.6 on 2025-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_remove_race_features_classfeature_spell_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='gain_subskills',
            field=models.ManyToManyField(blank=True, help_text='Select which sub-skills this feature grants proficiency in', related_name='gained_by_features', to='characters.subskill'),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='kind',
            field=models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table'), ('inherent_spell', 'Inherent Spell'), ('gain_proficiency', 'Gain Proficiency')], default='class_feat', help_text='What *type* of feature this is.', max_length=20),
        ),
        migrations.AlterField(
            model_name='racialfeature',
            name='kind',
            field=models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table'), ('inherent_spell', 'Inherent Spell'), ('gain_proficiency', 'Gain Proficiency'), ('inherent_spell', 'Inherent Spell')], default='inherent_spell', help_text='What *type* of feature this is.', max_length=20),
        ),
    ]
