# Generated by Django 5.1.6 on 2025-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_classsubclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubclass',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
