# Generated by Django 5.1.6 on 2025-08-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_alter_classfeature_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feats', to='characters.character')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.classfeat')),
            ],
            options={
                'verbose_name_plural': 'Character Feats',
                'unique_together': {('character', 'feat')},
            },
        ),
    ]
