# Generated by Django 5.1.6 on 2025-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_classfeature_gain_subskills_alter_classfeature_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='primary_ability',
            field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default='strength', help_text='Which ability gets the primary bonus', max_length=12),
        ),
        migrations.AlterField(
            model_name='background',
            name='secondary_ability',
            field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default='dexterity', help_text='Which ability gets the secondary bonus', max_length=12),
        ),
    ]
