# Generated by Django 5.1.6 on 2025-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_characterfeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MartialMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level_required', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('points_cost', models.PositiveIntegerField()),
                ('all_classes', models.BooleanField(default=False, help_text='If true, any class may take this mastery.')),
                ('classes', models.ManyToManyField(blank=True, to='characters.characterclass')),
            ],
        ),
    ]
