# Generated by Django 5.1.6 on 2025-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_alter_background_primary_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Select which pre-defined RacialFeatures apply to this Race', related_name='races', to='characters.racialfeature'),
        ),
    ]
