# Generated by Django 5.1.6 on 2025-04-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_alter_classsubclass_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeature',
            name='subclasses',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='subclass',
            field=models.ForeignKey(blank=True, help_text='If this is a Subclass feature, which subclass does it belong to?', null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.classsubclass'),
        ),
        migrations.AlterField(
            model_name='classsubclass',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
