# Generated by Django 5.1.6 on 2025-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_remove_classfeature_subclasses_classfeature_subclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeature',
            name='feat_type',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='feature_type',
            field=models.CharField(choices=[('class_trait', 'Class Trait'), ('class_feat', 'Class feat'), ('skill_feat', 'Skill feat'), ('martial_mastery', 'Martial Mastery'), ('subclass_feat', 'Subclass feature')], default='class_feat', help_text='Type of trait', max_length=100),
        ),
    ]
