# Generated by Django 5.1.6 on 2025-06-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_race_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racialfeature',
            options={'verbose_name': 'Racial Feature', 'verbose_name_plural': 'Racial Features'},
        ),

        # first, drop the old M2M on Race
        migrations.RemoveField(
            model_name='race',
            name='features',
        ),

        # then drop the old primary-key 'id' on RacialFeature
        migrations.RemoveField(
            model_name='racialfeature',
            name='id',
        ),

        # now add the OneToOneField → ClassFeature as the new primary key
        migrations.AddField(
            model_name='racialfeature',
            name='classfeature_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='characters.classfeature'
            ),
            preserve_default=False,
        ),

        # update all the FKs that pointed at RacialFeature or ClassFeature
        migrations.AlterField(
            model_name='characterfeature',
            name='feature',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='character_features',
                to='characters.classfeature'
            ),
        ),
        migrations.AlterField(
            model_name='characterfeature',
            name='racial_feature',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='racial_character_features',
                to='characters.racialfeature'
            ),
        ),
        migrations.AlterField(
            model_name='racefeatureoption',
            name='feature',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='race_options',
                to='characters.racialfeature'
            ),
        ),
        migrations.AlterField(
            model_name='racefeatureoption',
            name='grants_feature',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='race_granted_by_options',
                to='characters.racialfeature'
            ),
        ),
        migrations.AlterField(
            model_name='racialfeature',
            name='race',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='features',
                to='characters.race'
            ),
        ),
        migrations.AlterField(
            model_name='racialfeature',
            name='subrace',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='features',
                to='characters.subrace'
            ),
        ),

        # finally, remove all the old ClassFeature fields that were inherited
        migrations.RemoveField(model_name='racialfeature', name='code'),
        migrations.RemoveField(model_name='racialfeature', name='damage_type'),
        migrations.RemoveField(model_name='racialfeature', name='description'),
        migrations.RemoveField(model_name='racialfeature', name='formula'),
        migrations.RemoveField(model_name='racialfeature', name='has_options'),
        migrations.RemoveField(model_name='racialfeature', name='kind'),
        migrations.RemoveField(model_name='racialfeature', name='name'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_basic_failure'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_basic_success'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_critical_failure'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_critical_success'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_failure'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_granularity'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_required'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_success'),
        migrations.RemoveField(model_name='racialfeature', name='saving_throw_type'),
        migrations.RemoveField(model_name='racialfeature', name='uses'),
    ]
