# Generated by Django 5.1.6 on 2025-08-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_martialmastery'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterManualGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_grants', to='characters.character')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'characters'), ('model__in', ['classfeat', 'classfeature', 'racialfeature'])), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterFieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_notes', to='characters.character')),
            ],
            options={
                'unique_together': {('character', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CharacterFieldOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_overrides', to='characters.character')),
            ],
            options={
                'unique_together': {('character', 'key')},
            },
        ),
    ]
