# Generated by Django 5.1.6 on 2025-08-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_charactermanualgrant_characterfieldnote_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='characters.character')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('character', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='CharacterKnownSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('arcane', 'Arcane'), ('divine', 'Divine'), ('primal', 'Primal'), ('occult', 'Occult')], max_length=10)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='characters.character')),
                ('from_class', models.ForeignKey(blank=True, help_text='Optional: which class granted/learned this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characterclass')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.spell')),
            ],
            options={
                'unique_together': {('character', 'spell')},
            },
        ),
        migrations.CreateModel(
            name='CharacterMartialMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_picked', models.PositiveSmallIntegerField(help_text='Character level when selected')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='martial_masteries', to='characters.character')),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.martialmastery')),
            ],
            options={
                'unique_together': {('character', 'mastery')},
            },
        ),
        migrations.CreateModel(
            name='CharacterPreparedSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('arcane', 'Arcane'), ('divine', 'Divine'), ('primal', 'Primal'), ('occult', 'Occult')], max_length=10)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_spells', to='characters.character')),
                ('source_feature', models.ForeignKey(blank=True, limit_choices_to={'kind': 'spell_table'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.classfeature')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.spell')),
            ],
            options={
                'unique_together': {('character', 'spell', 'rank', 'origin')},
            },
        ),
        migrations.CreateModel(
            name='CharacterWeaponEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary')])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_weapons', to='characters.character')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.weapon')),
            ],
            options={
                'unique_together': {('character', 'slot_index')},
            },
        ),
    ]
