# Generated by Django 5.1.6 on 2025-04-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_remove_classfeature_feat_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeature',
            name='subclass',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='subclasses',
            field=models.ManyToManyField(blank=True, help_text='If this is a Subclass feature, choose which subclass(es) grant it.', related_name='class_features', to='characters.classsubclass'),
        ),
        migrations.AlterField(
            model_name='classsubclass',
            name='base_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='characters.characterclass'),
        ),
    ]
