# Generated by Django 5.1.6 on 2025-06-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_alter_racialfeature_options_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='spell',
            name='class_feature',
            field=models.OneToOneField(blank=True, help_text='If this is an inherent‐spell feature, store its full Spell here.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherent_spell_data', to='characters.classfeature'),
        ),
    ]
