# Generated by Django 5.1.6 on 2025-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_remove_classfeature_subclass_classfeature_subclasses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubclass',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
