# Generated by Django 5.1.6 on 2025-08-21 17:49

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_characteractivation_characterknownspell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='believers_and_ideals',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='bonds_relationships',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='iconic_flaws',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='iconic_strengths',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='outlook',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ties_connections',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='worshipped_gods',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
