# Generated by Django 5.1.6 on 2025-04-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_alter_classsubclass_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubclass',
            name='system_type',
            field=models.CharField(choices=[('linear', 'Linear (fixed–level)'), ('modular_linear', 'Modular Linear (ordered tiers)'), ('modular_mastery', 'Modular Mastery (pick-and-master)')], default='linear', help_text='Linear: fixed subclass feature at specific levels.  Modular Linear: multiple tiered traits in strict order.  Modular Mastery: pick modules freely, gain mastery when prerequisites met.', max_length=20),
        ),
        migrations.AlterField(
            model_name='classsubclass',
            name='base_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='characters.characterclass'),
        ),
        migrations.AlterField(
            model_name='classsubclass',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
