# Generated by Django 5.1.6 on 2025-04-27 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_classsubclass_system_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubclassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Umbrella / Order name (e.g. Moon Circle)', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Sort order within this class')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclass_groups', to='characters.characterclass')),
            ],
            options={
                'ordering': ['character_class', 'order'],
                'unique_together': {('character_class', 'name')},
            },
        ),
        migrations.AddField(
            model_name='classsubclass',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Which umbrella / order this belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='characters.subclassgroup'),
        ),
    ]
