# Generated by Django 5.1.6 on 2025-08-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_character_believers_and_ideals_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='weapon',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('bludgeoning', 'Bludgeoning'), ('piercing', 'Piercing'), ('slashing', 'Slashing')], default=None, max_length=30, null=True),
        ),
    ]
