# Generated by Django 5.1.6 on 2025-04-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_subclassgroup_classsubclass_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeature',
            name='subclasses',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='subclass_group',
            field=models.ForeignKey(blank=True, help_text='If this is a subclass_choice, pick one umbrella to choose from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_features', to='characters.subclassgroup'),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='feature_type',
            field=models.CharField(choices=[('class_trait', 'Class Trait'), ('class_feat', 'Class feat'), ('skill_feat', 'Skill feat'), ('martial_mastery', 'Martial Mastery'), ('subclass_choice', 'Subclass choice')], default='class_feat', help_text='Type of trait', max_length=100),
        ),
    ]
