# Generated by Django 5.1.6 on 2025-08-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_remove_weapon_damagae_type_weapon_damage_type'),
    ]

    operations = [

        migrations.AddField(
            model_name='martialmastery',
            name='allowed_traits',
            field=models.ManyToManyField(blank=True, help_text='Check the weapon traits this mastery targets (shown when ‘Weapon trait restriction’ is enabled).', related_name='masteries', to='characters.weapontrait'),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='allowed_weapons',
            field=models.ManyToManyField(blank=True, help_text='Check the weapons this mastery is usable with (shown when ‘Weapon restriction’ is enabled).', related_name='masteries', to='characters.weapon'),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='restrict_to_traits',
            field=models.BooleanField(default=False, help_text='If checked, this mastery only applies to weapons having any of the selected traits.'),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='restrict_to_weapons',
            field=models.BooleanField(default=False, help_text='If checked, this mastery only applies to selected weapons.'),
        ),
    ]
