# Generated by Django 5.1.6 on 2025-04-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_remove_classfeature_subclasses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subclassgroup',
            options={'ordering': ['character_class', 'name']},
        ),
        migrations.RemoveField(
            model_name='subclassgroup',
            name='order',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='subclasses',
            field=models.ManyToManyField(blank=True, help_text='For subclass_feat, which subclasses receive this?', related_name='features', to='characters.classsubclass'),
        ),
        migrations.AddField(
            model_name='classsubclass',
            name='modular_rules',
            field=models.JSONField(blank=True, help_text='Extra numbers for modular systems.  eg. {"modules_per_mastery":2, "ability_req":{"0":13,"1":15}}', null=True),
        ),
        migrations.AddField(
            model_name='subclassgroup',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='feature_type',
            field=models.CharField(choices=[('class_trait', 'Class Trait'), ('class_feat', 'Class Feat'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('subclass_choice', 'Subclass Choice'), ('subclass_feat', 'Subclass Feature')], default='class_feat', help_text='Type of trait', max_length=100),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='subclass_group',
            field=models.ForeignKey(blank=True, help_text='For a subclass_choice, pick the umbrella shown to the player.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_features', to='characters.subclassgroup'),
        ),
        migrations.AlterField(
            model_name='classsubclass',
            name='system_type',
            field=models.CharField(choices=[('linear', 'Linear'), ('modular_linear', 'Modular Linear'), ('modular_mastery', 'Modular Mastery')], default='linear', max_length=20),
        ),
    ]
