# Generated by Django 5.1.6 on 2025-08-25 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


# Only allow known choices to be copied
_VALID_DAMAGE = {"bludgeoning", "piercing", "slashing"}


def copy_single_to_array(apps, schema_editor):
    Weapon = apps.get_model('characters', 'Weapon')
    # This runs before we remove the old column, so it's safe to read damage_type
    for w in Weapon.objects.all():
        val = getattr(w, 'damage_type', None)
        if val in _VALID_DAMAGE:
            w.damage_types = [val]
        else:
            # keep empty list if no/invalid value
            w.damage_types = []
        # save only the new field to keep it quick
        w.save(update_fields=['damage_types'])


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_armor_dex_cap_martialmastery_allowed_traits_and_more'),
    ]

    operations = [
        # 1) Add the new multi-select column
        migrations.AddField(
            model_name='weapon',
            name='damage_types',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=30,
                    choices=[('bludgeoning', 'Bludgeoning'),
                             ('piercing', 'Piercing'),
                             ('slashing', 'Slashing')]
                ),
                default=list,
                blank=True,
                help_text='Select one or more damage types.',
                size=None,
            ),
        ),

        # 2) Copy data from old single-select into the new array
        migrations.RunPython(copy_single_to_array, migrations.RunPython.noop),

        # 3) Now it is safe to drop the old column
        migrations.RemoveField(
            model_name='weapon',
            name='damage_type',
        ),

        # (Your other unrelated changes can stay as-is)
        migrations.AddField(
            model_name='armor',
            name='strength_requirement',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True,
                help_text='Minimum Strength to wear effectively (optional).'
            ),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='action_cost',
            field=models.CharField(
                blank=True, null=True, max_length=10,
                choices=[
                    ('action_1', 'One Action'),
                    ('action_2', 'Two Actions'),
                    ('action_3', 'Three Actions'),
                    ('reaction', 'Reaction'),
                    ('free', 'Free Action'),
                ],
                help_text='How many actions this mastery takes to use (if applicable).',
            ),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_normal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
