# Generated by Django 5.1.6 on 2025-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_remove_classsubclass_system_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclassgroup',
            name='system_type',
            field=models.CharField(choices=[('linear', 'Linear (fixed level)'), ('modular_linear', 'Modular Linear (tiered)'), ('modular_mastery', 'Modular Mastery (pick & master)')], default='linear', max_length=20),
        ),
    ]
