# Generated by Django 5.1.6 on 2025-08-26 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_armor_dex_cap_martialmastery_is_rare'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevelfeature',
            name='num_picks',
            field=models.PositiveSmallIntegerField(default=1, help_text='Only for subclass_choice: how many features the player may pick at this level.'),
        ),
        migrations.AddField(
            model_name='subclassgroup',
            name='modules_per_mastery',
            field=models.PositiveSmallIntegerField(default=2, help_text='Default modules needed to earn +1 mastery rank (used by modular_mastery groups).'),
        ),
        migrations.AlterField(
            model_name='martialmastery',
            name='is_rare',
            field=models.BooleanField(default=False, help_text='If checked, this mastery is rare/unusual.'),
        ),
        migrations.CreateModel(
            name='SubclassMasteryUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='Mastery rank > 0 (e.g., 1, 2, 3)')),
                ('unlock_level', models.PositiveIntegerField(help_text='Class level at which this rank becomes reachable')),
                ('modules_required', models.PositiveIntegerField(default=2, help_text='CUMULATIVE modules from the SAME subclass required to claim this rank.')),
                ('subclass_group', models.ForeignKey(help_text='Which umbrella this rule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mastery_unlocks', to='characters.subclassgroup')),
            ],
            options={
                'ordering': ['subclass_group', 'rank'],
                'unique_together': {('subclass_group', 'rank')},
            },
        ),
    ]
