# Generated by Django 5.1.6 on 2025-08-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_classlevelfeature_num_picks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialmastery',
            name='allowed_damage_types',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed damage types. Uses Weapon.DAMAGE_CHOICES values (e.g. 'bludgeoning')."),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='restrict_to_damage',
            field=models.BooleanField(default=False, help_text='If checked, this mastery only applies to weapons that deal any of the selected damage types.'),
        ),
    ]
