# Generated by Django 5.1.6 on 2025-08-29 14:32

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0030_martialmastery_allowed_damage_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialmastery',
            name='available_masteries_formula',
            field=models.CharField(blank=True, default=None, help_text="(Only for kind='martial_mastery') Formula for how many masteries are available at this class level.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='martial_points_formula',
            field=models.CharField(blank=True, default=None, help_text="(Only for kind='martial_mastery') Formula for the Martial Mastery points this class grants.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='martialmastery',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
