# Generated by Django 5.1.6 on 2025-04-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0030_alter_classfeature_formula_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='cantrips_formula',
            field=models.CharField(blank=True, help_text="Formula for number of cantrips known per class level, e.g. '1 + level//4'", max_length=100),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='spells_known_formula',
            field=models.CharField(blank=True, help_text="Formula for number of spells known per class level, e.g. '2 + level//2'", max_length=100),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='feature_type',
            field=models.CharField(choices=[('class_trait', 'Class Trait'), ('class_feat', 'Class Feat'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('subclass_choice', 'Subclass Choice'), ('subclass_feat', 'Subclass Feature'), ('spell_table', 'Spell Slot Table')], default='class_feat', help_text='Type of trait', max_length=100),
        ),
        migrations.CreateModel(
            name='SpellSlotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10'), (11, 'Level 11'), (12, 'Level 12'), (13, 'Level 13'), (14, 'Level 14'), (15, 'Level 15'), (16, 'Level 16'), (17, 'Level 17'), (18, 'Level 18'), (19, 'Level 19'), (20, 'Level 20')], help_text='Character level')),
                ('slot1', models.PositiveSmallIntegerField(default=0, help_text='1st-rank slots')),
                ('slot2', models.PositiveSmallIntegerField(default=0, help_text='2nd-rank slots')),
                ('slot3', models.PositiveSmallIntegerField(default=0, help_text='3rd-rank slots')),
                ('slot4', models.PositiveSmallIntegerField(default=0, help_text='4th-rank slots')),
                ('slot5', models.PositiveSmallIntegerField(default=0, help_text='5th-rank slots')),
                ('slot6', models.PositiveSmallIntegerField(default=0, help_text='6th-rank slots')),
                ('slot7', models.PositiveSmallIntegerField(default=0, help_text='7th-rank slots')),
                ('slot8', models.PositiveSmallIntegerField(default=0, help_text='8th-rank slots')),
                ('slot9', models.PositiveSmallIntegerField(default=0, help_text='9th-rank slots')),
                ('slot10', models.PositiveSmallIntegerField(default=0, help_text='10th-rank slots')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_slot_rows', to='characters.classfeature')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('feature', 'level')},
            },
        ),
    ]
