# Generated by Django 5.1.6 on 2025-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0031_martialmastery_available_masteries_formula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='martialmastery',
            name='available_masteries_formula',
        ),
        migrations.RemoveField(
            model_name='martialmastery',
            name='martial_points_formula',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='available_masteries_formula',
            field=models.CharField(blank=True, default=None, help_text="(Only for kind='martial_mastery') Formula for how many masteries are available at this class level.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='martial_points_formula',
            field=models.CharField(blank=True, default=None, help_text="(Only for kind='martial_mastery') Formula for the Martial Mastery points this class grants.", max_length=100, null=True),
        ),
    ]
