# Generated by Django 5.1.6 on 2025-05-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0031_classfeature_cantrips_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='modify_proficiency_amount',
            field=models.CharField(blank=True, help_text="Tier name or +/- adjustment (e.g. '+1', 'Expert')", max_length=10),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='modify_proficiency_target',
            field=models.CharField(blank=True, choices=[('armor', 'Armor'), ('dodge', 'Dodge'), ('perception', 'Perception'), ('initiative', 'Initiative'), ('dc', 'Spell/DC'), ('reflex', 'Reflex Save'), ('fortitude', 'Fortitude Save'), ('will', 'Will Save'), ('weapon', 'Weapon')], help_text='Which proficiency to modify', max_length=20),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='feature_type',
            field=models.CharField(choices=[('class_trait', 'Class Trait'), ('class_feat', 'Class Feat'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('subclass_choice', 'Subclass Choice'), ('subclass_feat', 'Subclass Feature'), ('spell_table', 'Spell Slot Table'), ('modify_proficiency', 'Modify Proficiency')], default='class_feat', help_text='Type of trait', max_length=100),
        ),
    ]
