# Generated by Django 5.1.6 on 2025-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_classfeature_modify_proficiency_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubclass',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
