# Generated by Django 5.1.6 on 2025-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_remove_martialmastery_available_masteries_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialmastery',
            name='required_ability',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], help_text='Which ability this requirement targets.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='required_ability_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum ability score needed (e.g., 13).', null=True),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='restrict_by_ability',
            field=models.BooleanField(default=False, help_text='If checked, a character must meet the minimum score below.'),
        ),
    ]
