# Generated by Django 5.1.6 on 2025-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0033_martialmastery_required_ability_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classproficiencyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classproficiencyprogress',
            name='armor_group',
            field=models.CharField(blank=True, choices=[('unarmored', 'Unarmored'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('shield', 'Shield')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classproficiencyprogress',
            name='weapon_group',
            field=models.CharField(blank=True, choices=[('unarmed', 'Unarmed'), ('simple', 'Simple'), ('martial', 'Martial'), ('special', 'Special')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classproficiencyprogress',
            unique_together={('character_class', 'proficiency_type', 'at_level', 'armor_group', 'weapon_group')},
        ),
    ]
