# Generated by Django 5.1.6 on 2025-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0033_alter_classsubclass_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='For class_trait & subclass_choice: checked = active (uses), unchecked = passive (static bonus)'),
        ),
    ]
