# Generated by Django 5.1.6 on 2025-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0034_classfeature_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeature',
            name='is_active',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='activity_type',
            field=models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], default='active', help_text='For class_trait & subclass_choice: active consumes uses; passive is static.', max_length=7),
        ),
    ]
