# Generated by Django 5.1.6 on 2025-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0034_alter_classproficiencyprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='kind',
            field=models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table'), ('inherent_spell', 'Inherent Spell'), ('core_proficiency', 'Add Core Proficiency (Armor/Weapon)'), ('gain_resistance', 'Gain Resistance')], default='class_feat', help_text='What *type* of feature this is.', max_length=20),
        ),
    ]
