# Generated by Django 5.1.6 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0035_alter_classfeature_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_amount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Flat reduction (only when mode = reduction).', null=True),
        ),
        migrations.AddField(
            model_name='specialitemtraitvalue',
            name='gain_resistance_types',
            field=models.JSONField(blank=True, default=list, help_text='List of damage types this trait applies to.'),
        ),
    ]
