# Generated by Django 5.1.6 on 2025-05-02 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0035_remove_classfeature_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifier for formulas, e.g. 'bloodline_points'", unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_level', models.IntegerField(default=0, help_text='How many points this class gains per level')),
                ('max_points', models.IntegerField(default=0, help_text='Maximum pool size (0 = no cap)')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='characters.characterclass')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.resourcetype')),
            ],
            options={
                'unique_together': {('character_class', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='CharacterResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='characters.character')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.resourcetype')),
            ],
            options={
                'unique_together': {('character', 'resource_type')},
            },
        ),
    ]
