# Generated by Django 5.1.6 on 2025-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0036_specialitemtraitvalue_gain_resistance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialmastery',
            name='trait_match_mode',
            field=models.CharField(choices=[('any', 'Match ANY of the selected traits'), ('all', 'Match ALL of the selected traits')], default='any', help_text='When restricting to traits, require the weapon to match ANY vs ALL selected traits.', max_length=3),
        ),
    ]
