# Generated by Django 5.1.6 on 2025-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0036_resourcetype_classresource_characterresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclassgroup',
            name='modular_rules',
            field=models.JSONField(blank=True, help_text='Extra numbers for modular systems (e.g. {modules_per_mastery:2, max_mastery_3:1})', null=True),
        ),
    ]
