# Generated by Django 5.1.6 on 2025-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0037_martialmastery_trait_match_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='mastery_rank',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Rank 0'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4')], help_text="(modular_mastery) For scope='subclass_feat': the module's rank (0–4). For scope='gain_subclass_feat': the MAX rank this level allows you to pick up to.", null=True),
        ),
        migrations.AlterField(
            model_name='subclassgroup',
            name='modular_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Example: {"modules_per_mastery":2, "picks_per_trigger":1, "max_mastery_rank":3}'),
        ),
        migrations.AlterField(
            model_name='subclassgroup',
            name='system_type',
            field=models.CharField(choices=[('linear', 'Linear (fixed level)'), ('modular_linear', 'Modular Linear (tiered)'), ('modular_mastery', 'Modular Mastery (pick & master)')], default='linear', max_length=32),
        ),
    ]
