# Generated by Django 5.1.6 on 2025-05-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0037_subclassgroup_modular_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classresource',
            name='points_per_level',
            field=models.CharField(blank=True, help_text="Formula for points per level, e.g. '1 + level//3'", max_length=100),
        ),
    ]
