# Generated by Django 5.1.6 on 2025-09-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_alter_classfeature_mastery_rank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classproficiencyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classproficiencyprogress',
            name='armor_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.armor'),
        ),
        migrations.AddField(
            model_name='classproficiencyprogress',
            name='weapon_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.weapon'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='key_abilities',
            field=models.ManyToManyField(blank=True, help_text='Select exactly one or two key ability scores for this class.', to='characters.abilityscore'),
        ),
        migrations.AlterUniqueTogether(
            name='classproficiencyprogress',
            unique_together={('character_class', 'proficiency_type', 'at_level', 'armor_group', 'weapon_group', 'armor_item', 'weapon_item')},
        ),
    ]
