# Generated by Django 5.1.6 on 2025-09-07 16:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_alter_classfeature_mastery_rank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classproficiencyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='starting_skills_formula',
            field=models.CharField(blank=True, help_text="Formula for the number of skills you start trained in at level 1. Examples: '2', '2 + int_mod', '1 + floor((intelligence-10)/2)'.", max_length=200),
        ),
        migrations.AddField(
            model_name='classproficiencyprogress',
            name='armor_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.armor'),
        ),
        migrations.AddField(
            model_name='classproficiencyprogress',
            name='weapon_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.weapon'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='key_abilities',
            field=models.ManyToManyField(blank=True, help_text='Select exactly one or two key ability scores for this class.', to='characters.abilityscore'),
        ),
        migrations.AlterField(
            model_name='classproficiencyprogress',
            name='weapon_group',
            field=models.CharField(blank=True, choices=[('unarmed', 'Unarmed'), ('simple', 'Simple'), ('martial', 'Martial'), ('special', 'Special'), ('black_powder', 'Black Powder')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='category',
            field=models.CharField(choices=[('simple', 'Simple'), ('martial', 'Martial'), ('special', 'Special'), ('black powder', 'Black Powder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bludgeoning', 'Bludgeoning'), ('piercing', 'Piercing'), ('slashing', 'Slashing'), ('explosive', 'Explosives')], max_length=30), blank=True, default=list, help_text='Select one or more damage types.', size=None),
        ),
        migrations.AlterUniqueTogether(
            name='classproficiencyprogress',
            unique_together={('character_class', 'proficiency_type', 'at_level', 'armor_group', 'weapon_group', 'armor_item', 'weapon_item')},
        ),
    ]
