# Generated by Django 5.1.6 on 2025-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_alter_classresource_points_per_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classresource',
            name='points_per_level',
        ),
        migrations.AddField(
            model_name='classresource',
            name='formula',
            field=models.CharField(blank=True, help_text="Formula for how many points this class grants at a given level, e.g. 'ceil(level/2) + strength_modifier', or 'floor(level/3)+1', etc.", max_length=100),
        ),
    ]
