# Generated by Django 5.1.6 on 2025-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0039_alter_classproficiencyprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classproficiencyprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classproficiencyprogress',
            name='at_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='classproficiencyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('armor_group__isnull', True), ('armor_item__isnull', True), ('weapon_group__isnull', True), ('weapon_item__isnull', True)), fields=('character_class', 'proficiency_type', 'at_level'), name='cpp_unique_generic_per_level'),
        ),
        migrations.AddConstraint(
            model_name='classproficiencyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('armor_group__isnull', False), ('armor_item__isnull', True), ('weapon_group__isnull', True), ('weapon_item__isnull', True)), fields=('character_class', 'proficiency_type', 'at_level', 'armor_group'), name='cpp_unique_armor_group_per_level'),
        ),
        migrations.AddConstraint(
            model_name='classproficiencyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('armor_group__isnull', True), ('armor_item__isnull', True), ('weapon_group__isnull', False), ('weapon_item__isnull', True)), fields=('character_class', 'proficiency_type', 'at_level', 'weapon_group'), name='cpp_unique_weapon_group_per_level'),
        ),
        migrations.AddConstraint(
            model_name='classproficiencyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('armor_group__isnull', True), ('armor_item__isnull', False), ('weapon_group__isnull', True), ('weapon_item__isnull', True)), fields=('character_class', 'proficiency_type', 'at_level', 'armor_item'), name='cpp_unique_armor_item_per_level'),
        ),
        migrations.AddConstraint(
            model_name='classproficiencyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('armor_group__isnull', True), ('armor_item__isnull', True), ('weapon_group__isnull', True), ('weapon_item__isnull', False)), fields=('character_class', 'proficiency_type', 'at_level', 'weapon_item'), name='cpp_unique_weapon_item_per_level'),
        ),
    ]
