# Generated by Django 5.1.6 on 2025-05-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0039_remove_classresource_points_per_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterresource',
            name='maximum',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='action_type',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('bonus', 'Bonus Action'), ('reaction', 'Reaction')], help_text='What kind of action this ability consumes.', max_length=10, null=True, verbose_name='Action Required'),
        ),
    ]
