# Generated by Django 5.1.6 on 2025-09-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0040_alter_classproficiencyprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classproficiencyprogress',
            name='cpp_unique_generic_per_level',
        ),
        migrations.RemoveConstraint(
            model_name='classproficiencyprogress',
            name='cpp_unique_armor_group_per_level',
        ),
        migrations.RemoveConstraint(
            model_name='classproficiencyprogress',
            name='cpp_unique_weapon_group_per_level',
        ),
        migrations.RemoveConstraint(
            model_name='classproficiencyprogress',
            name='cpp_unique_armor_item_per_level',
        ),
        migrations.RemoveConstraint(
            model_name='classproficiencyprogress',
            name='cpp_unique_weapon_item_per_level',
        ),
    ]
