# Generated by Django 5.1.6 on 2025-05-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0040_remove_characterresource_maximum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='action_type',
            field=models.CharField(blank=True, choices=[('action_1', 'One Action'), ('action_2', 'Two Actions'), ('action_3', 'Three Actions'), ('reaction', 'Reaction'), ('free', 'Free Action')], help_text='What kind of action this ability consumes.', max_length=10, null=True, verbose_name='Action Required'),
        ),
    ]
