# Generated by Django 5.1.6 on 2025-09-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0042_seed_proficiency_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProficiencyUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rank', models.CharField(choices=[('untrained', 'Untrained'), ('trained', 'Trained'), ('expert', 'Expert'), ('master', 'Master'), ('legendary', 'Legendary')], max_length=12)),
                ('to_rank', models.CharField(choices=[('untrained', 'Untrained'), ('trained', 'Trained'), ('expert', 'Expert'), ('master', 'Master'), ('legendary', 'Legendary')], max_length=12)),
                ('points', models.PositiveSmallIntegerField()),
                ('min_level', models.PositiveIntegerField(default=0, help_text='Minimum CHARACTER level to perform this upgrade')),
            ],
            options={
                'ordering': ['points', 'min_level', 'from_rank', 'to_rank'],
                'unique_together': {('from_rank', 'to_rank')},
            },
        ),
        migrations.CreateModel(
            name='ClassSkillFeatGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_level', models.PositiveIntegerField()),
                ('num_picks', models.PositiveSmallIntegerField(default=1, help_text='How many skill feat picks at this level')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_feat_grants', to='characters.characterclass')),
            ],
            options={
                'ordering': ['character_class', 'at_level'],
                'unique_together': {('character_class', 'at_level')},
            },
        ),
        migrations.CreateModel(
            name='ClassSkillPointGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_level', models.PositiveIntegerField()),
                ('points_awarded', models.PositiveSmallIntegerField(help_text='Skill points granted at this class level')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_point_grants', to='characters.characterclass')),
            ],
            options={
                'ordering': ['character_class', 'at_level'],
                'unique_together': {('character_class', 'at_level')},
            },
        ),
    ]
