# Generated by Django 5.1.6 on 2025-05-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0043_remove_classfeature_feature_type_classfeature_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='kind',
            field=models.CharField(choices=[('class_feat', 'Class Feat'), ('class_trait', 'Class Trait'), ('skill_feat', 'Skill Feat'), ('martial_mastery', 'Martial Mastery'), ('modify_proficiency', 'Modify Proficiency'), ('spell_table', 'Spell Slot Table')], default='class_feat', help_text='What *type* of feature this is.', max_length=20),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='scope',
            field=models.CharField(choices=[('class_feat', 'Class Feature'), ('subclass_feat', 'Subclass Feature'), ('subclass_choice', 'Subclass Choice')], default='class_feat', help_text='Does this belong to the base class, a subclass, or is it a subclass-choice?', max_length=20),
        ),
    ]
