# Generated by Django 5.1.6 on 2025-09-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0043_skillproficiencyupgrade_classskillfeatgrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='skill_points_per_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many skill points this class grants each time you gain a level in it.'),
        ),
        migrations.CreateModel(
            name='CharacterSkillPointTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive=grant/refund, negative=spend')),
                ('source', models.CharField(choices=[('level_award', 'Level Award'), ('spend', 'Spend on Skill'), ('refund', 'Refund (Retrain)'), ('admin', 'Admin/Adjustment')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('at_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characterclass')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_point_txs', to='characters.character')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
