# Generated by Django 5.1.6 on 2025-05-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0044_alter_classfeature_kind_alter_classfeature_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='spells_prepared_formula',
            field=models.CharField(blank=True, help_text="Formula for number of spells you can prepare per class level, e.g. 'intelligence//2 + level//3'", max_length=100),
        ),
    ]
