# Generated by Django 5.1.6 on 2025-09-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0045_fix_race_subrace_fk_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitem',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.equipmentslot'),
        ),
    ]
