# Generated by Django 5.1.6 on 2025-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0046_alter_classfeature_formula_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('physical_bludgeoning', 'Physical Bludgeoning'), ('physical_slashing', 'Physical Slashing'), ('physical_piercing', 'Physical Piercing'), ('explosive', 'Explosive'), ('magical_bludgeoning', 'Magical Bludgeoning'), ('magical_slashing', 'Magical Slashing'), ('magical_piercing', 'Magical Piercing'), ('acid', 'Acid'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('thunder', 'Thunder'), ('true', 'True')], help_text='If this feature deals damage, pick its damage type (optional).', max_length=25, null=True),
        ),
    ]
