# Generated by Django 5.1.6 on 2025-09-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0046_alter_specialitem_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialmastery',
            name='allowed_range_types',
            field=models.JSONField(blank=True, default=list, help_text="Values: 'melee' and/or 'ranged'. Leave empty if not restricting."),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='restrict_to_range',
            field=models.BooleanField(default=False, help_text='When on, limit to the selected weapon range types (melee/ranged).'),
        ),
    ]
