# Generated by Django 5.1.6 on 2025-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0047_classfeature_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_granularity',
            field=models.CharField(blank=True, choices=[('basic', 'Basic (Success / Failure)'), ('normal', 'Normal (Crit Success, Success, Failure, Crit Failure)')], help_text='How many result‐levels to allow', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_required',
            field=models.BooleanField(default=False, help_text='Does this trait allow a saving throw?'),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_type',
            field=models.CharField(blank=True, choices=[('reflex_save', 'Reflex Save'), ('fortitude_save', 'Fortitude Save'), ('will_save', 'Will Save')], help_text='Which saving throw this trait uses', max_length=20, null=True),
        ),
    ]
