# Generated by Django 5.1.6 on 2025-05-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0048_classfeature_saving_throw_granularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_basic_outcomes',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], help_text='What happens on basic save', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_normal_outcomes',
            field=models.CharField(blank=True, choices=[('critical_success', 'Critical Success'), ('success', 'Success'), ('failure', 'Failure'), ('critical_failure', 'Critical Failure')], help_text='What happens on full save table', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='saving_throw_granularity',
            field=models.CharField(blank=True, choices=[('basic', 'Basic (Success / Failure)'), ('normal', 'Normal (Crit Success / Success / Failure / Crit Failure)')], help_text='Simple or full save table?', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='saving_throw_required',
            field=models.BooleanField(default=False, help_text='Does this ability allow a saving throw?'),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='saving_throw_type',
            field=models.CharField(blank=True, choices=[('reflex', 'Reflex'), ('fortitude', 'Fortitude'), ('will', 'Will')], help_text='Which saving throw?', max_length=10, null=True),
        ),
    ]
