# Generated by Django 5.1.6 on 2025-09-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaignnote_options'),
        ('characters', '0048_character_status_pendingbackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingbackground',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_backgrounds', to='campaigns.campaign'),
        ),
    ]
