# Generated by Django 5.1.6 on 2025-09-20 20:59

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0049_alter_pendingbackground_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='backstory',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
