# Generated by Django 5.1.6 on 2025-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0049_classfeature_saving_throw_basic_outcomes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeature',
            name='saving_throw_basic_outcomes',
        ),
        migrations.RemoveField(
            model_name='classfeature',
            name='saving_throw_normal_outcomes',
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_basic_failure',
            field=models.CharField(blank=True, help_text='What happens on a basic save: Failure', max_length=255),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_basic_success',
            field=models.CharField(blank=True, help_text='What happens on a basic save: Success', max_length=255),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_critical_failure',
            field=models.CharField(blank=True, help_text='What happens on a full save: Critical Failure', max_length=255),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_critical_success',
            field=models.CharField(blank=True, help_text='What happens on a full save: Critical Success', max_length=255),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_failure',
            field=models.CharField(blank=True, help_text='What happens on a full save: Failure', max_length=255),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='saving_throw_success',
            field=models.CharField(blank=True, help_text='What happens on a full save: Success', max_length=255),
        ),
    ]
