# Generated by Django 5.1.6 on 2025-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0050_remove_classfeature_saving_throw_basic_outcomes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('level_prerequisite', models.CharField(blank=True, max_length=32)),
                ('feat_type', models.CharField(max_length=64)),
                ('class_name', models.CharField(blank=True, max_length=64)),
                ('race', models.CharField(blank=True, max_length=64)),
                ('tags', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
                ('classification', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField()),
                ('effect', models.TextField(blank=True)),
                ('upcast_effect', models.TextField(blank=True)),
                ('saving_throw', models.CharField(blank=True, max_length=64)),
                ('casting_time', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
                ('components', models.CharField(max_length=64)),
                ('range', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=64)),
                ('origin', models.CharField(max_length=64)),
                ('sub_origin', models.CharField(blank=True, max_length=64)),
                ('mastery_req', models.CharField(blank=True, max_length=64)),
                ('tags', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
