# Generated by Django 5.1.6 on 2025-05-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0051_classfeat_spell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='school',
        ),
    ]
