# Generated by Django 5.1.6 on 2025-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0051_character_copper_character_gold_character_silver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialmastery',
            name='allowed_weapon_groups',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed weapon groups (e.g. ['simple','martial']). Uses WEAPON_GROUPS values."),
        ),
        migrations.AddField(
            model_name='martialmastery',
            name='restrict_to_weapon_groups',
            field=models.BooleanField(default=False, help_text='If checked, this mastery only applies to selected weapon groups.'),
        ),
    ]
