# Generated by Django 5.1.6 on 2025-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0052_remove_spell_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
