# Generated by Django 5.1.6 on 2025-05-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0053_alter_spell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
