# Generated by Django 5.1.6 on 2025-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0053_characteritem_is_custom_characteritem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(blank=True, help_text="Leave blank to use your race's default.", null=True),
        ),
    ]
