# Generated by Django 5.1.6 on 2025-05-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0055_alter_spell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='classification',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='mastery_req',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='origin',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='saving_throw',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='sub_origin',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target',
            field=models.CharField(max_length=512),
        ),
    ]
