# Generated by Django 5.1.6 on 2025-10-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0055_charactershareinvite_characterviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='details_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_details/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_categories', to='characters.character')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('character', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_notes/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='characters.character')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='characters.notecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
