# Generated by Django 5.1.6 on 2025-10-05 15:49

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0056_character_details_image_notecategory_characternote'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='appearance',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
