# Generated by Django 5.1.6 on 2025-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0057_character_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='action_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='damage_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='formula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='formula_target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='modify_proficiency_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='modify_proficiency_target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_basic_failure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_basic_success',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_critical_failure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_critical_success',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_failure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='saving_throw_success',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitemtraitvalue',
            name='uses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
