# Generated by Django 5.1.6 on 2025-10-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0059_prestigeclass_prestigeprerequisite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPrestigeLevelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestige_level', models.PositiveSmallIntegerField(help_text='1, 2, 3, … within this prestige class')),
                ('counts_as', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.characterclass')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_choices', to='characters.characterprestigeenrollment')),
            ],
            options={
                'ordering': ['enrollment', 'prestige_level'],
                'unique_together': {('enrollment', 'prestige_level')},
            },
        ),
    ]
