# Generated by Django 5.1.6 on 2025-11-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0060_characterprestigelevelchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterManualFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_feats', to='characters.character')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.classfeat')),
            ],
            options={
                'ordering': ['feat__name', 'id'],
                'unique_together': {('character', 'feat')},
            },
        ),
    ]
