# Generated by Django 5.1.6 on 2025-11-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0061_charactermanualfeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('kind', models.CharField(choices=[('standard', 'Standard'), ('toggle', 'Toggle'), ('ap_standard', 'AP Standard'), ('ap_toggle', 'AP Toggle')], max_length=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
            options={
                'ordering': ['roll_code', 'id'],
            },
        ),
    ]
