# Generated by Django 5.1.6 on 2025-11-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0062_rollmodifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterfieldoverride',
            name='value',
            field=models.CharField(max_length=999),
        ),
    ]
