# Generated by Django 5.1.6 on 2025-11-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0063_alter_characterfieldoverride_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterprestigelevelchoice',
            options={'ordering': ['character', 'prestige_class', 'prestige_level']},
        ),
        migrations.AlterUniqueTogether(
            name='characterprestigelevelchoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='characterprestigelevelchoice',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestige_choices', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterprestigelevelchoice',
            name='prestige_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestige_choices', to='characters.prestigeclass'),
        ),
        migrations.AlterField(
            model_name='characterprestigelevelchoice',
            name='counts_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestige_counts_as', to='characters.characterclass'),
        ),
        migrations.AlterField(
            model_name='characterprestigelevelchoice',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_legacy', to='characters.characterprestigeenrollment'),
        ),
        migrations.AlterField(
            model_name='characterprestigelevelchoice',
            name='prestige_level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='characterprestigelevelchoice',
            unique_together={('character', 'prestige_class', 'prestige_level')},
        ),
    ]
