# Generated by Django 5.1.6 on 2025-11-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0064_alter_characterprestigelevelchoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterprestigelevelchoice',
            name='enrollment',
        ),
        migrations.AlterField(
            model_name='characterprestigelevelchoice',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestige_choices', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='characterprestigelevelchoice',
            name='prestige_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestige_choices', to='characters.prestigeclass'),
        ),
        migrations.DeleteModel(
            name='CharacterPrestigeEnrollment',
        ),
    ]
