# Generated by Django 5.1.6 on 2025-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0065_remove_characterprestigelevelchoice_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprestigelevelchoice',
            name='char_level_at_gain',
            field=models.PositiveIntegerField(blank=True, help_text='Character level at which this prestige level was taken.', null=True),
        ),
    ]
