# Generated by Django 5.1.6 on 2025-11-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0066_characterprestigelevelchoice_char_level_at_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attunement_max',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximum number of magic items this character can be attuned to at once.'),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='is_equipped',
            field=models.BooleanField(default=False),
        ),
    ]
