# Generated by Django 5.1.6 on 2025-11-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0067_character_attunement_max_characteritem_is_equipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterWearable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearables', to='characters.character')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_in_wearable_slots', to='characters.characteritem')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_by', to='characters.wearableslot')),
            ],
            options={
                'unique_together': {('character', 'slot')},
            },
        ),
    ]
