# Generated by Django 5.1.6 on 2026-01-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0068_characterwearable'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='armor_defence',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
