# Generated by Django 5.1.6 on 2026-01-14 10:56

from django.db import migrations

from django.db import migrations
from django.db.models import F
from django.db.models.functions import Replace
from django.db.models import Value

def forwards(apps, schema_editor):
    MartialMastery = apps.get_model("characters", "MartialMastery")

    # Chain two case-sensitive replaces at the DB level
    MartialMastery.objects.update(
        description=Replace(
            Replace(F("description"), Value("Dodge"), Value("Defence")),
            Value("dodge"),
            Value("defence"),
        )
    )
class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0070_armor_CHANGE'),
    ]

    operations = [
                migrations.RunPython(forwards, migrations.RunPython.noop),

    ]
