# Generated by Django 5.1.6 on 2026-02-11 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0071_replace_dodge_with_defence_in_mastery_desc'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('public_intro', models.TextField(blank=True, help_text='Shown on the public changelog page above entries in this category.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AuditTrackedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('track_creates', models.BooleanField(default=True)),
                ('track_updates', models.BooleanField(default=True)),
                ('track_deletes', models.BooleanField(default=True)),
                ('track_m2m', models.BooleanField(default=False)),
                ('include_fields', models.JSONField(blank=True, help_text='Optional list of field names to include. If blank/null, includes all concrete fields (minus exclude_fields).', null=True)),
                ('exclude_fields', models.JSONField(blank=True, default=list, help_text="Field names to ignore (ex: ['updated_at', 'last_seen']).")),
                ('content_type', models.OneToOneField(limit_choices_to=models.Q(('app_label', 'characters')), on_delete=django.db.models.deletion.CASCADE, related_name='characters_audit_tracking', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ModelChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('m2m', 'M2M Change')], db_index=True, max_length=12)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_group', models.CharField(blank=True, help_text="Public heading/group (ex: 'Patch 0.9.1' or 'Feb 2026'). Leave blank to group by date.", max_length=120)),
                ('public_title', models.CharField(blank=True, max_length=200)),
                ('public_summary', models.TextField(blank=True)),
                ('public_body', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='characters.changecategory')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_change_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'characters')), on_delete=django.db.models.deletion.CASCADE, related_name='characters_change_logs', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id', 'occurred_at'], name='characters__content_01362a_idx'), models.Index(fields=['is_published', 'published_at'], name='characters__is_publ_221d43_idx')],
            },
        ),
    ]
