# Generated by Django 5.1.6 on 2026-03-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0072_changecategory_audittrackedmodel_modelchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PatchNoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patch_usages', to='characters.changecategory')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_categories', to='characters.patchnote')),
            ],
            options={
                'ordering': ('sort_order', 'category__sort_order', 'category__name'),
                'unique_together': {('patch', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PatchChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('change_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patch_links', to='characters.modelchangelog')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_changes', to='characters.patchnote')),
                ('patch_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='characters.patchnotecategory')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'unique_together': {('patch', 'change_log')},
            },
        ),
    ]
