# Generated by Django 5.1.6 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0073_patchnote_patchnotecategory_patchchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchchange',
            name='patch_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='characters.patchnotecategory'),
        ),
    ]
