# Generated by Django 5.1.6 on 2026-03-01 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0074_alter_patchchange_patch_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchchange',
            name='patch_category',
        ),
        migrations.AddField(
            model_name='patchchange',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patch_changes', to='characters.changecategory'),
        ),
        migrations.DeleteModel(
            name='PatchNoteCategory',
        ),
    ]
