# Generated by Django 5.1.6 on 2026-04-22 16:46

from django.db import migrations, models


def forwards(apps, schema_editor):
    Weapon = apps.get_model("characters", "Weapon")

    batch = []

    for w in Weapon.objects.all():
        changed = False

        # If melee, keep all distance bands empty
        if getattr(w, "range_type", None) == "melee":
            if (
                w.range_effective is not None
                or w.range_suboptimal is not None
                or w.range_maximum is not None
            ):
                w.range_effective = None
                w.range_suboptimal = None
                w.range_maximum = None
                changed = True

        else:
            old_effective = w.range_effective
            old_max = w.range_maximum

            # old effective becomes new sub-optimal
            if old_effective is not None:
                old_effective = int(old_effective)
                w.range_suboptimal = old_effective

                # new effective = old effective reduced by 25%
                # floor(old * 0.75)
                w.range_effective = max(1, (old_effective * 3) // 4)
                changed = True

            # new maximum = old max increased by 25%
            # ceil(old * 1.25)
            if old_max is not None:
                old_max = int(old_max)
                bumped_max = (old_max * 5 + 3) // 4

                # never let maximum fall below sub-optimal
                if w.range_suboptimal is not None:
                    bumped_max = max(bumped_max, int(w.range_suboptimal))

                w.range_maximum = bumped_max
                changed = True

        if changed:
            batch.append(w)

    if batch:
        Weapon.objects.bulk_update(
            batch,
            ["range_effective", "range_suboptimal", "range_maximum"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0075_remove_patchchange_patch_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weapon",
            old_name="range_normal",
            new_name="range_effective",
        ),
        migrations.RenameField(
            model_name="weapon",
            old_name="range_max",
            new_name="range_maximum",
        ),
        migrations.AddField(
            model_name="weapon",
            name="range_suboptimal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]