# Generated by Django 5.1.6 on 2026-04-22 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0076_rename_range_normal_weapon_range_effective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='category',
            field=models.CharField(choices=[('simple', 'Simple'), ('martial', 'Martial'), ('special', 'Special'), ('black_powder', 'Black Powder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bludgeoning', 'Bludgeoning'), ('piercing', 'Piercing'), ('slashing', 'Slashing'), ('explosive', 'Explosive')], max_length=30), blank=True, default=list, help_text='Select one or more damage types.', size=None),
        ),
    ]
