# Generated by Django 5.1.6 on 2025-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated aliases (e.g., On hit, onhit).')),
                ('case_sensitive', models.BooleanField(default=False)),
                ('whole_word', models.BooleanField(default=True, help_text='Match whole words only (recommended).')),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher runs first; prefer longer/important terms.')),
            ],
        ),
    ]
