# Generated by Django 5.1.6 on 2025-09-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_join_password_campaignmessage_campaignnote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignnote',
            options={'ordering': ['-created_at']},
        ),
    ]
