# Generated by Django 5.1.6 on 2025-10-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaignnote_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('hp', models.PositiveIntegerField(default=1)),
                ('armor', models.IntegerField(default=0)),
                ('dodge', models.IntegerField(default=0)),
                ('str_score', models.IntegerField(default=10)),
                ('dex_score', models.IntegerField(default=10)),
                ('con_score', models.IntegerField(default=10)),
                ('int_score', models.IntegerField(default=10)),
                ('wis_score', models.IntegerField(default=10)),
                ('cha_score', models.IntegerField(default=10)),
                ('will_save', models.IntegerField(default=0)),
                ('reflex_save', models.IntegerField(default=0)),
                ('fortitude_save', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
                ('stealth', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('resistances', models.TextField(blank=True, help_text='Free text for resistances/notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnemyAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_type', models.CharField(choices=[('passive', 'Passive'), ('active', 'Active')], max_length=8)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='campaigns.enemytype')),
            ],
            options={
                'ordering': ['ability_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EncounterEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_override', models.CharField(blank=True, max_length=160)),
                ('max_hp', models.PositiveIntegerField()),
                ('current_hp', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='campaigns.encounter')),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='campaigns.enemytype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
