# Generated by Django 5.1.6 on 2025-10-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_enemytype_encounter_enemyability_encounterenemy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='enemytype',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Leave blank for Global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemy_types', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='enemy_types', to='campaigns.enemytag'),
        ),
        migrations.AddConstraint(
            model_name='enemytype',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', True)), fields=('name',), name='uniq_enemytype_global_name'),
        ),
        migrations.AddConstraint(
            model_name='enemytype',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='uniq_enemytype_campaign_name'),
        ),
    ]
