# Generated by Django 5.1.6 on 2025-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_enemytag_enemytype_campaign_alter_enemytype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounterenemy',
            name='initiative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enemyability',
            name='action_cost',
            field=models.CharField(choices=[('free', 'Free'), ('1', '1 Action'), ('2', '2 Actions'), ('3', '3 Actions'), ('reaction', 'Reaction'), ('-', '— (Passive/None)')], default='-', max_length=9),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
    ]
