# Generated by Django 5.1.6 on 2025-10-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_damageevent_encounterparticipant'),
        ('characters', '0057_character_appearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damageevent',
            name='enemy',
        ),
        migrations.AddField(
            model_name='damageevent',
            name='attacker_enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_events', to='campaigns.encounterenemy'),
        ),
        migrations.AddField(
            model_name='damageevent',
            name='target_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_damage_events', to='characters.character'),
        ),
        migrations.AddField(
            model_name='damageevent',
            name='target_enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_events', to='campaigns.encounterenemy'),
        ),
        migrations.AddField(
            model_name='encounterenemy',
            name='side',
            field=models.CharField(choices=[('enemy', 'Enemy'), ('neutral', 'Neutral'), ('ally', 'Ally')], db_index=True, default='enemy', max_length=7),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='category',
            field=models.CharField(choices=[('monster', 'Monster'), ('npc', 'NPC')], db_index=True, default='monster', max_length=8),
        ),
        migrations.AlterField(
            model_name='damageevent',
            name='attacker_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_damage_events', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='encounterparticipant',
            name='role',
            field=models.CharField(choices=[('pc', 'Player')], default='pc', max_length=3),
        ),
    ]
