# Generated by Django 5.1.6 on 2025-10-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_remove_damageevent_enemy_damageevent_attacker_enemy_and_more'),
        ('characters', '0057_character_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyitem',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partyitem',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_party_items', to='characters.character'),
        ),
    ]
