# Generated by Django 5.1.6 on 2025-10-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_partyitem_claimed_at_partyitem_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemytype',
            name='athletics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='speed',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
