# Generated by Django 5.1.6 on 2026-01-04 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_enemytype_athletics_enemytype_speed'),
        ('characters', '0068_characterwearable'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemytype',
            name='acrobatics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='basic_attack_action',
            field=models.CharField(choices=[('1', '1 Action'), ('2', '2 Actions'), ('3', '3 Actions'), ('reaction', 'Reaction'), ('free', 'Free')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='basic_attack_ap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='basic_attack_damage',
            field=models.CharField(blank=True, help_text='e.g. 2d8+6', max_length=120),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='basic_attack_name',
            field=models.CharField(default='Strike', max_length=120),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='basic_attack_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='basic_attack_to_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='can_cast_spells',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='crit_threshold',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='insight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='martial_masteries',
            field=models.ManyToManyField(blank=True, related_name='enemy_types', to='characters.martialmastery'),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='enemy_types', to='characters.spell'),
        ),
        migrations.CreateModel(
            name='EnemyDamageResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('reduction', 'Reduction (flat)'), ('resistance', 'Resistance (half)')], default='reduction', max_length=12)),
                ('damage_type', models.CharField(choices=[('all', 'All Damage'), ('physical_all', 'All Physical'), ('physical_non_magical', 'Non-magical Physical'), ('physical_bludgeoning', 'Physical Bludgeoning'), ('physical_slashing', 'Physical Slashing'), ('physical_piercing', 'Physical Piercing'), ('explosive', 'Explosive'), ('magical_bludgeoning', 'Magical Bludgeoning'), ('magical_slashing', 'Magical Slashing'), ('magical_piercing', 'Magical Piercing'), ('acid', 'Acid'), ('cold', 'Cold'), ('fire', 'Fire'), ('force', 'Force'), ('lightning', 'Lightning'), ('necrotic', 'Necrotic'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('radiant', 'Radiant'), ('thunder', 'Thunder'), ('true', 'True')], max_length=25)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_resistances', to='campaigns.enemytype')),
            ],
            options={
                'ordering': ['damage_type', 'mode'],
                'unique_together': {('enemy_type', 'mode', 'damage_type')},
            },
        ),
    ]
