# Generated by Django 5.1.6 on 2026-03-12 12:16

import django.db.models.deletion
from django.db import migrations, models

from django.db import migrations, models
import django.db.models.deletion


def copy_old_category_to_kind(apps, schema_editor):
    EnemyType = apps.get_model("campaigns", "EnemyType")

    for obj in EnemyType.objects.all().only("id", "category", "kind"):
        old = (obj.category or "").strip().lower()

        if old in {"monster", "npc"}:
            obj.kind = old
        else:
            obj.kind = "monster"

        obj.save(update_fields=["kind"])


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_enemytype_acrobatics_enemytype_basic_attack_action_and_more"),  # KEEP THIS AS WHATEVER YOUR REAL PREVIOUS MIGRATION IS
    ]

    operations = [
        migrations.CreateModel(
            name="EnemyCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Enemy categories",
            },
        ),

        # Step 1: add kind separately
        migrations.AddField(
            model_name="enemytype",
            name="kind",
            field=models.CharField(
                choices=[("monster", "Monster"), ("npc", "NPC")],
                default="monster",
                max_length=8,
                db_index=True,
            ),
        ),

        # Step 2: copy old text category -> new kind
        migrations.RunPython(copy_old_category_to_kind, migrations.RunPython.noop),

        # Step 3: remove OLD text category field
        migrations.RemoveField(
            model_name="enemytype",
            name="category",
        ),

        # Step 4: add NEW FK category field
        migrations.AddField(
            model_name="enemytype",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enemy_types",
                to="campaigns.enemycategory",
            ),
        ),
    ]