# Generated by Django 5.1.6 on 2026-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_enemycategory_enemytype_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemytype',
            name='dodge',
            field=models.IntegerField(default=0, verbose_name='Defence'),
        ),
    ]
